### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by asotog** [chrisgladd/grunt-phantomcss#43]
hi,
when running `sudo npm install grunt-phantomcss --save-dev`, i'm getting this

``
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at GitHubResolver.GitResolver._cleanup (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/lib/core/resolvers/GitResolver.js:158:26)
    at /Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/lib/core/resolvers/GitResolver.js:66:25
    at Promise.apply (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:752:41)
    at /Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:1337:14
    at flush (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

Console trace:
Trace
    at StandardRenderer.error (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/lib/renderers/StandardRenderer.js:69:17)
    at Logger.updateNotifier.packageName (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/bin/bower:113:18)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/lib/commands/install.js:25:16
    at _rejected (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:808:24)
    at /Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:752:41)
    at /Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html/node_modules/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.0.3
Node version: 0.10.33
OS: Darwin 14.0.0 x64

npm ERR! grunt-phantomcss@0.2.3 postinstall: `node ./node_modules/bower/bin/bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grunt-phantomcss@0.2.3 postinstall script.
npm ERR! This is most likely a problem with the grunt-phantomcss package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-phantomcss
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "grunt-phantomcss" "--save-dev"
npm ERR! cwd /Users/alejandrosoto/Downloads/ProjectsInfo/XXX/repo/html
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
``

im on
mac os yosemite
node v0.10.33
bower v1.4.1
grunt-cli v0.1.13
grunt v0.4.5

thanks,

**Comment by rafaelcamargo** [comment]
Getting that same error:
`npm ERR! grunt-phantomcss@0.2.3 postinstall: node ./node_modules/bower/bin/bower install`

```
Win 8.1 64bits
Cygwin terminal
```
**package.json**
```
{
  "name": "ng-rise",
  "version": "0.1.1",
  "repository": {
    "type": "git",
    "url": "https://github.com/rafaelcamargo/ng-rise"
  },
  "devDependencies": {
    "bower": "~1.3.12",
    "grunt": "~0.4.5",
    "grunt-bower-install-simple": "^1.1.0",
    "grunt-cli": "~v0.1.13",
    "grunt-concat-in-order": "^0.1.6",
    "grunt-contrib-copy": "^0.8.0",
    "grunt-contrib-stylus": "~0.20.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-http-server": "^1.2.0",
    "grunt-karma": "~0.10.1",
    "jasmine-core": "~2.3.0",
    "karma": "~0.12.31",
    "karma-chrome-launcher": "^0.1.12",
    "karma-cli": "0.0.4",
    "karma-coverage": "~0.3.1",
    "karma-jasmine": "~0.3.5",
    "karma-ng-html2js-preprocessor": "^0.1.2",
    "karma-phantomjs-launcher": "~0.1.4"
  }
}
```
**bower.json**
```
{
  "name": "ng-rise",
  "version": "0.1.1",
  "dependencies": {
    "angular": "~1.3.x",
    "angular-route": "~1.3.x"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.15"
  },
  "resolutions": {
    "angular": "~1.3.x"
  }
}
```

**Comment by rafaelcamargo** [comment]
[SOLVED] I have followed the instructions by @designjockey on: https://github.com/chrisgladd/grunt-phantomcss/issues/27
